import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { flagships,getFlagship } from "../../brand-data";
import { IntakeLink } from "../../components/IntakeLink";
import { MarketingShell } from "../../components/MarketingShell";

type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return flagships.map((item)=>({slug:item.slug}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const item=getFlagship(slug);if(!item)notFound();return{title:item.name,description:item.description,alternates:{canonical:`/flagships/${item.slug}`}}}
export default async function FlagshipDetail({params}:Props){const {slug}=await params;const item=getFlagship(slug);if(!item)notFound();const index=flagships.findIndex((entry)=>entry.slug===item.slug);const next=flagships[index+1];return <MarketingShell><section className="parity-detail"><div className="parity-detail-media"><Image src={item.image} alt={`${item.name} visual`} fill priority sizes="(max-width: 900px) 100vw, 50vw"/></div><div className="parity-detail-copy"><div className="parity-status"><i/> FLAGSHIP {item.step} // ACTIVE</div><p className="parity-eyebrow">{item.eyebrow}</p><h1>{item.name}</h1><p className="parity-detail-lede">{item.headline}</p><p>{item.description}</p><IntakeLink className="parity-button parity-primary" service={item.name} source="flagship-page">START THIS ENGAGEMENT <span>↗</span></IntakeLink></div></section><section className="parity-deliverables"><div><span>WHAT THIS STAGE CREATES</span><h2>THE OUTPUT IS<br/><em>USABLE.</em></h2></div><ol>{item.outcomes.map((outcome,i)=><li key={outcome}><span>0{i+1}</span><b>{outcome}</b></li>)}</ol></section><section className="parity-stage-context"><p className="parity-eyebrow">WHY THIS COMES {item.step==="01"?"FIRST":item.step==="05"?"LAST":"HERE"}</p><h2>{item.step==="01"?"CLARITY BEFORE CONSTRUCTION.":item.step==="02"?"ARCHITECTURE BEFORE ASSETS.":item.step==="03"?"INFRASTRUCTURE BEFORE THE ASK.":item.step==="04"?"READINESS BEFORE THE MONEY.":"ACTIVATE WHAT HAS BEEN BUILT."}</h2><p>{item.step==="04"?"A lender should not have to guess how the company works, where the money goes, or how repayment becomes possible. We close those gaps before the application.":"Every stage protects the work that came before it and creates the conditions required for the stage that follows."}</p>{next?<Link href={`/flagships/${next.slug}`}>NEXT: {next.name.toUpperCase()} →</Link>:<Link href="/divisions">MEET THE BUILD DIVISIONS →</Link>}</section></MarketingShell>}
