export const flagships = [
  { slug: "extraction", step: "01", name: "Idea Extraction Session™", shortName: "Extraction", eyebrow: "CLARIFY THE THING", headline: "GET THE WHOLE IDEA OUT OF YOUR HEAD—WITHOUT FLATTENING IT.", description: "A guided working session that retrieves the real vision, contradictions included, and identifies the outcome, audience, obstacles, and missing pieces before anyone starts building the wrong thing.", image: "/brand/approved/POLAR_DEFINITIVE_FULL_BODY_MASTER.png", outcomes: ["Founder-intelligence capture", "Problem and opportunity definition", "Contradiction mapping", "Priority and next-move clarity"] },
  { slug: "blueprint", step: "02", name: "The Bipolarized Blueprint™", shortName: "Blueprint", eyebrow: "ARCHITECT THE THING", headline: "TURN THE COMPLEX IDEA INTO AN EXECUTABLE ENTERPRISE.", description: "The flagship architecture engagement that defines what the enterprise is, who it serves, what must be built, which BPEI divisions are involved, what comes first, and how the founder’s original intent stays intact.", image: "/brand/divisions/polar/blueprint.webp", outcomes: ["Business architecture", "Positioning and offer system", "Operating model", "Sequenced execution roadmap"] },
  { slug: "buildout", step: "03", name: "Business Infrastructure Buildout", shortName: "Buildout", eyebrow: "BUILD THE SYSTEM", headline: "REPLACE HUSTLE, MEMORY, AND GUESSWORK WITH INFRASTRUCTURE.", description: "We build the documents, workflows, governance, automation pathways, brand systems, digital surfaces, and operational backbone the Blueprint calls for.", image: "/brand/approved/BPEI_BRANDED_ENVIRONMENT_HD.png", outcomes: ["Governance and SOP stack", "Workflow and automation design", "Brand and digital infrastructure", "Institutional memory system"] },
  { slug: "funding-readiness", step: "04", name: "Funding Readiness", shortName: "Funding", eyebrow: "ENGINEER READINESS", headline: "DON’T JUST APPLY FOR MONEY. BUILD A CASE THAT MAKES SENSE.", description: "The BPEI Lender Readiness System™ aligns the entity, documents, numbers, narrative, risk controls, and capital-use plan before the formal ask. Readiness is designed from day one and verified here.", image: "/brand/approved/POLAR_INTERFACE_PROJECTION.png", outcomes: ["Entity and compliance audit", "Application document architecture", "Funding narrative and financial story", "Capital deployment roadmap"] },
  { slug: "deployment", step: "05", name: "Enterprise Deployment", shortName: "Deployment", eyebrow: "MAKE THE THING OPERATE", headline: "MOVE FROM READY-ON-PAPER TO LIVE, CONNECTED, AND REVENUE-FACING.", description: "We coordinate launch, connect the working systems, activate the public-facing assets, verify the customer path, and establish the measurement required to keep improving after launch.", image: "/brand/approved/POLAR_ORIGINAL_CHARACTER_REVEAL.png", outcomes: ["Launch coordination", "System and integration activation", "Customer-path verification", "Measurement and optimization plan"] },
] as const;

export const divisions = [
  { slug: "sav-vidzgen", name: "Sav.VidzGen™", code: "SVG-001", polar: "The Visual Storyteller", image: "/brand/divisions/polar/sav-vidzgen.webp", video: "/media/polar/products/sav-vidzgen.mp4", description: "Commercials, explainers, social video, branded media, and AI-assisted production systems.", capabilities: ["Video production", "Commercials", "Explainers", "Social content", "AI-assisted media"] },
  { slug: "dr-docx", name: "Dr.Docx™", code: "DOC-001", polar: "The Documentation Specialist", image: "/brand/divisions/polar/dr-docx.webp", video: "/media/polar/products/dr-docx.mp4", description: "SOPs, policies, agreements, manuals, proposals, and enterprise knowledge systems.", capabilities: ["SOPs", "Policies", "Proposals", "Manuals", "Knowledge systems"] },
  { slug: "blueprint", name: "Blueprint™", code: "BLP-001", polar: "The Enterprise Architect", image: "/brand/divisions/polar/blueprint.webp", video: "/media/polar/products/blueprint.mp4", description: "Business architecture that converts founder intelligence into an executable operating model.", capabilities: ["Architecture", "Business plans", "Strategy", "Operating models", "Execution roadmaps"] },
  { slug: "brandforge", name: "BrandForge™", code: "BRF-001", polar: "The Identity Engineer", image: "/brand/divisions/polar/brandforge.webp", video: "/media/polar/products/brandforge.mp4", description: "Identity engineering, visual systems, brand standards, campaigns, and production assets.", capabilities: ["Brand identity", "Visual systems", "Messaging", "Campaigns", "Creative production"] },
  { slug: "launchpad", name: "LaunchPad™", code: "LCH-001", polar: "The Formation Navigator", image: "/brand/divisions/polar/launchpad.webp", video: "/media/polar/products/launchpad.mp4", description: "Formation, registration, compliance, banking readiness, and operational business setup.", capabilities: ["Formation", "Registration", "Compliance", "Banking readiness", "Business credit"] },
  { slug: "nexus", name: "Nexus™", code: "NXS-001", polar: "The Systems Connector", image: "/brand/divisions/polar/nexus.webp", video: "/media/polar/products/nexus.mp4", description: "AI agents, integrations, APIs, CRM systems, websites, portals, and workflow automation.", capabilities: ["AI systems", "Automation", "Websites", "CRM", "Integrations"] },
  { slug: "pulse", name: "Pulse™", code: "PLS-001", polar: "The Intelligence Analyst", image: "/brand/divisions/polar/pulse.webp", video: "/media/polar/products/pulse.mp4", description: "Dashboards, KPIs, forecasts, reporting, analytics, and executive business intelligence.", capabilities: ["Dashboards", "KPIs", "Forecasting", "Reporting", "Analytics"] },
  { slug: "vault", name: "Vault™", code: "VLT-001", polar: "The Memory Keeper", image: "/brand/divisions/polar/vault.webp", video: "/media/polar/products/vault.mp4", description: "Institutional memory, governed archives, knowledge graphs, version control, and asset registries.", capabilities: ["Archives", "Knowledge graphs", "Version control", "Asset registries", "Institutional memory"] },
  { slug: "cipher", name: "Cipher™", code: "CPH-001", polar: "The Digital Guardian", image: "/brand/divisions/polar/cipher.webp", video: "/media/polar/products/cipher.mp4", description: "Cybersecurity architecture, identity protection, compliance, monitoring, and digital defense.", capabilities: ["Security architecture", "Identity protection", "Monitoring", "Compliance", "Digital defense"] },
] as const;

export function getFlagship(slug: string) { return flagships.find((item) => item.slug === slug); }
export function getDivision(slug: string) { return divisions.find((item) => item.slug === slug); }
