import Link from "next/link";
import { IntakeLink } from "./components/IntakeLink";
import { MarketingShell } from "./components/MarketingShell";
import type { Metadata } from "next";

export const metadata: Metadata = { alternates: { canonical: "/" } };

export default function Home() {
  return <MarketingShell>
    <section className="home-hero"><div className="home-hero-image" aria-hidden="true"/><div className="parity-gridlines" aria-hidden="true"/><div className="home-hero-content"><div className="parity-status"><i/> SYSTEM ACTIVE <span>BP-WEB-7709</span></div><p className="parity-eyebrow">INNOVATION INFRASTRUCTURE</p><h1>YOUR IDEA ISN’T TOO MUCH.<br/><em>IT’S UNDER-ARCHITECTED.</em></h1><p className="home-hero-copy">BI POLARIZE ENTERPRISES turns unconventional, founder-dependent ideas into structured, documented, automation-ready enterprises that can operate, grow, and get to the bag.</p><div className="parity-actions"><IntakeLink className="parity-button parity-primary">TELL US ABOUT YOUR THING™ <span>↗</span></IntakeLink><Link className="parity-button parity-ghost" href="/flagships">SEE THE BUILD PATH</Link></div></div><div className="parity-scrollmark">WHO · WHAT · WHY <span>↓</span></div></section>
    <section className="parity-signal"><span>WHO WE ARE</span><i>◆</i><span>WHAT WE DO</span><i>◆</i><span>WHY YOU NEED US</span></section>
    <section className="home-answer who"><div className="answer-index">01 // WHO WE ARE</div><div><p className="parity-eyebrow">THE BUSINESS BEHIND THE BLUEPRINT</p><h2>WE ARE AN INNOVATION<br/><em>INFRASTRUCTURE FIRM.</em></h2></div><div className="answer-copy"><p>Not an agency. Not a motivational consulting studio. BI POLARIZE is the architecture lab for founders whose ideas do not fit neatly into somebody else’s template.</p><p>We protect the original vision while engineering the structure required to make it usable, fundable, repeatable, and durable.</p></div></section>
    <section className="home-answer what"><div className="answer-index">02 // WHAT WE DO</div><div><p className="parity-eyebrow">ALL THE BUSINESS FOR YOUR BUSINESS™</p><h2>WE TURN THE THING<br/><em>INTO A SYSTEM.</em></h2></div><div className="answer-copy"><p>We extract the founder intelligence, architect the operating model, build the infrastructure, engineer funding readiness, and coordinate deployment.</p><p>Five flagship engagements move the work from raw idea to functioning enterprise. Nine specialized divisions build what the Blueprint requires.</p><div className="parity-inline-actions"><Link href="/flagships">EXPLORE FLAGSHIPS →</Link><Link href="/divisions">MEET THE DIVISIONS →</Link></div></div></section>
    <section className="home-answer why"><div className="answer-index">03 // WHY YOU NEED US</div><div><p className="parity-eyebrow">FOUNDERS SHOULD BE THE SOURCE CODE—NOT THE BOTTLENECK</p><h2>HUSTLE IS NOT<br/><em>INFRASTRUCTURE.</em></h2></div><div className="answer-copy"><p>If everything depends on what you remember, personally explain, or fix at 2 a.m., you do not own a scalable system. You own an exhausting job wearing a company logo.</p><p>We make the business less dependent on your constant presence without stripping away what makes it yours.</p></div></section>
    <section className="home-close"><div className="parity-gridlines"/><p className="parity-eyebrow">OFF THE WALL AND OUT OF THE BOX™</p><h2>BRING US THE PART<br/><em>NOBODY ELSE UNDERSTANDS.</em></h2><p>You do not need a polished pitch. You need an honest starting point.</p><IntakeLink className="parity-button parity-primary">START THE EXTRACTION <span>↗</span></IntakeLink></section>
  </MarketingShell>;
}
